CREATE TABLE tb_kitchens (
  id BIGINT AUTO_INCREMENT NOT NULL,
  name varchar(80),

  PRIMARY KEY (id)
);

#IF YOU COMMENT INSIDE THESE FILES HERE, WILL CHANGE CHECKSUM AND ALL GOES TO SHIT, SO DON'T DO IT, ALWAYS MAKE SURE IN DB OR OTHER TOOL,
#DON'T MAKE MIGRATIONS FIRST, TEST BEFORE IN DB TO MAKE SURE IT IS OK, IF IT'S PROD TIME, IF IS A DEV TIME, FK IT, AND DON'T COMMENT AFTER SAVED
#PROBABBLY CAN FK CHECKSUM UP
#IT'S OK TO DROP DB IN DEV, NEEEVEER DO IN PRODUCTION LINE